### ISSUE TITLE
Cache  cookie free svg files.

### ISSUE THREAD

**Issue by martinfrances107** [wodby/drupal-varnish#1]
I like this module alot 

When running yslow against my development site I noticed that svg files are not being processed like other image formats

The default.vcl is as follows

    # Removing cookies for static content so Varnish caches these files.
    if (req.url ~ "(?i)\.(pdf|asc|dat|txt|doc|xls|ppt|tgz|csv|png|gif|jpeg|jpg|ico|swf|css|js)(\?.*)?$") {
        unset req.http.Cookie;
    }

I think we should add svg to the list of varnish cachable images.

PS 

Drupal8 is using svg files for icons and is in the process of adding many more.

here are some examples of svg icons that will appear on many pages.
core/misc/feed.svg
core/themes/bartik/logo.svg

**Comment by csandanov** [comment]
Done. Now svg is treated as any static content. Available in 4.1 tag
